"""add_strategic_indexes

Revision ID: c9e43326010e
Revises: 
Create Date: 2026-03-30 04:02:40.733891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e43326010e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ratings_from_uid'), 'ratings', ['from_uid'], unique=False)
    op.create_index(op.f('ix_ratings_session_id'), 'ratings', ['session_id'], unique=False)
    op.create_index(op.f('ix_ratings_to_uid'), 'ratings', ['to_uid'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_student_uid'), 'sessions', ['student_uid'], unique=False)
    op.create_index(op.f('ix_sessions_topper_id'), 'sessions', ['topper_id'], unique=False)
    op.create_index(op.f('ix_toppers_exam_cleared'), 'toppers', ['exam_cleared'], unique=False)
    op.create_index(op.f('ix_transactions_payment_id'), 'transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_uid'), 'transactions', ['user_uid'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_transactions_user_uid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_toppers_exam_cleared'), table_name='toppers')
    op.drop_index(op.f('ix_sessions_topper_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_student_uid'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_ratings_to_uid'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_session_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_from_uid'), table_name='ratings')
    # ### end Alembic commands ###
